---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории;
  - Пользователь должен иметь возможность фильтровать товары;
  - Сайт должен иметь мобильную версию;
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре;
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины;
  - Пользователь должен иметь возможность видеть на странице товара и в каталоге название, рейтинг, цену со скидкой и без нее;
  - Пользователь должен иметь возможность удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты;
  - Пользователь должен иметь возможность с просмотром и фильтрацией товаров, а также добавлением их в корзину.
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы;
  - Сайт должен быть безопасным и защищать данные пользователя;
  - Сайт нужно протестировать на совместимость с последними версиями браузеров;
  - Важно, чтобы сайт мог обрабатывать большое количество трафика;
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Соответствие законодательству;
  - Масштабируемость;
  - Локализация;
  - Интеграция;
  - Персонализация;
  - Интернационализация.
